import 'dotenv/config';
export const env = {
  PORT: Number(process.env.SERVER_PORT || 3000),
  DB_URL: process.env.MONGOOSE_URL,
  JWT_SECRET: process.env.JWT_SECRET as string,
  JWT_EXPIRATION: process.env.JWT_EXPIRATION as string,
  JWT_REFRESH_TOKEN: process.env.JWT_REFRESH_TOKEN as string,
  JWT_REFRESH_EXPIRATION: process.env.JWT_REFRESH_EXPIRATION as string,
  TRNX_SECRET: process.env.TRNX_SECRET as string,
  AGENT_APPROVED: process.env.AGENT_APPROVED as string,
  AGENT_SUSPEND: process.env.AGENT_SUSPEND as string,
  AGENT_REACTIVE: process.env.AGENT_REACTIVE as string,
  WALLET_ACTIVE: process.env.WALLET_ACTIVE as string,
  WALLET_BLOCKED: process.env.WALLET_BLOCKED as string,
  BCRYPT_PASS_NUMBER: Number(process.env.BCRYPT_PASS_NUMBER),
  MAX_NUMBER: Number(process.env.MAX_NUMBER),
  MIN_NUMBER: Number(process.env.MIN_NUMBER),
  CLOUDINARY_API_NAME: process.env.CLOUDINARY_API_NAME as string,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY as string,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET as string,
};
